### ISSUE TITLE
Reduce Shotgun Shell Casing sound by 25-33%

### ISSUE THREAD

**Issue by tunbridgep** [tunbridgep/gmdx-vrsd-fork#12]
Currently, the shell casing is quite obvious, to the point of being very noticeable during combat.

It should be reduced in volume to reduce it's presence. Players listening for it should hear it, but it shouldn't intrude into the regular soundscape too much.

For more information about adding/editing sounds for Unreal/DeusEx, look here:
https://www.offtopicproductions.com/tacks/HowToAddCustomSoundEffects.html

**Comment by ISuckM8** [comment]
Done, see https://github.com/tunbridgep/gmdx-vrsd-fork/pull/13
