### ISSUE TITLE
Tool requirement next to complexity should be Required/InventoryAmount instead of the current implementation 

### ISSUE THREAD

**Issue by ISuckM8** [tunbridgep/gmdx-vrsd-fork#31]
Title

**Comment by tunbridgep** [comment]
Why?

It makes logical sense the way it is. 2/4 or "2 out of 4" lockpicks required is how language generally works and how we measure other things.

How often do you see interfaces say things like:

1/2 objectives complete
2/5 locations discovered

etc

Everything works this way

I agree it can look weird when it says something like 5/1, which reads like "You have 5 of the 1 lockpicks required", but it's still much better than 1/5 which reads as if you're short by 4 lockpicks.

In the worst case, the red colour coding should additionally communicate how this works.
