### ISSUE TITLE
Scoping breaks foe or ally identifier 

### ISSUE THREAD

**Issue by ISuckM8** [tunbridgep/gmdx-vrsd-fork#33]
If you scope with a weapon, in my case the sniper rifle, crossbow won't change from white to red when you aim at enemies.

Possible causes: no clue, it used to work before I believe so maybe you'll know something.

**Comment by tunbridgep** [comment]
I believe this is caused by #24. Will need to check more thoroughly

**Comment by tunbridgep** [comment]
Fixed by 8ae3aef
