### ISSUE TITLE
Credits Amount doesn't display properly in Dialog Menus

### ISSUE THREAD

**Issue by tunbridgep** [tunbridgep/gmdx-vrsd-fork#41]
On certain screen resolutions, the Credits display is all messed up, and only shows a small amount of text.

**Comment by juuuulian-s** [comment]
![image](https://github.com/tunbridgep/gmdx-vrsd-fork/assets/107623369/611d3d4c-131c-4dc0-94e8-74aa99dd6165)
1360x768

**Comment by tunbridgep** [comment]
Tested at 1360x768, can't reproduce

**Comment by tunbridgep** [comment]
Can't reproduce after multiple attempts. No other user has reported problems.
