### ISSUE TITLE
Security Bot 3 doesn't show Disabled text after loading a save game

### ISSUE THREAD

**Issue by tunbridgep** [tunbridgep/gmdx-vrsd-fork#9]
I just loaded the game, and the bots which I had previously disabled weren't showing the Disabled text:

![image](https://github.com/tunbridgep/gmdx-vrsd-fork/assets/31608726/39fdf313-e719-4a2f-a439-a7ec10ed2acc)

However, the large security bot still shows the text:

![image](https://github.com/tunbridgep/gmdx-vrsd-fork/assets/31608726/4de4c37a-141d-4aad-b2f8-190d278d4cfd)

My guess is this is something I broke when I implemented the Hacking overhaul and the Camera/Turret reboot text, but it may also be a GMDX bug.

How to reproduce:
1. Load Area51 map
2. Use an EMP grenade or Spy Drone to disable the Security 3 bots
3. Save the game and exit
4. Reload
5. The disabled text will be missing

I would start by looking in `AugmentationDisplayWindow.uc`

**Comment by ISuckM8** [comment]
Fixed in https://github.com/tunbridgep/gmdx-vrsd-fork/pull/10

This was essentially an issue with RoSo forgetting to put brackets around both health and EMP
